// src/app/core/services/translate.service.ts
import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

type Lang = 'en' | 'ar';

const DICT: Record<Lang, Record<string, string>> = {
  en: {
    home: 'Home',
    hosting: 'Hosting',
    dedicated: 'Dedicated Servers',
    vps: 'VPS Hosting',
    promos: 'Promos',
    contact: 'Contact us',
    orderNow: 'Get Now',
    getStarted: 'Get Started',
    choosePlan: 'Choose the Plan',
    whyChoose: 'Why Choose TopServers For Your Dedicated Server Hosting?',
    dedicatedIntro: 'TopServers provides reliable dedicated servers with configurable CPU, RAM, storage and network options. Choose from curated configurations or filter to find the exact machine you need.',
    filterServers: 'Filter servers',
    cpuCores: 'CPU cores',
    ram: 'RAM (GB)',
    brand: 'Brand',
    maxPrice: 'Max price (USD)',
    noDedicatedFound: 'No dedicated servers found.',
    fullBannerTitle: 'Perfect <span class="text-base">Servers</span> Service For You',
    getHosting: 'Get Hosting',
    whyChooseUs: 'Why <span class="text-base">Choose Us</span>',
    chooseUsDesc: 'We go beyond servers to provide performance, security, and support that empowers your online success.',
    smartWorkTitle: 'Our Smart Work',
    smartWorkDesc: 'Intelligent automation for optimal performance and hassle-free management.',
    emailTitle: 'Professional Email',
    emailDesc: 'Professional email hosting included with every plan to build your brand identity.',
    supportTitle: 'Dedicated 24/7 Support',
    supportDesc: 'Round-the-clock expert support from our in-house team, whenever you need it.',
    serverProtectionTitle: 'Server Level Protection',
    serverProtectionDesc: 'Proactive, enterprise-grade security monitoring to defend against modern threats.',
    cloudIntegrationTitle: 'Cloud Integration',
    cloudIntegrationDesc: 'Scalable, resilient cloud infrastructure that grows with your traffic demands.',
    hostingPlanTitle: 'Hosting Plan',
    hostingPlanDesc: 'Find the perfect fit with our flexible plans, designed for projects of any size.',
    viewMoreAdvantages: 'View More Advantages',
    servicesTitle: 'Our <span class="text-base">Services</span>',
    servicesDesc: 'Choose the hosting plan that best fits your needs and budget.',
    tabDedicated: 'Dedicated Servers',
    tabVps: 'VPS Hosting',
    tabDedicatedTitle: '<span class="text-base">Dedicated</span> Servers',
    tabVpsTitle: '<span class="text-base">VPS</span> Hosting',
    tabListItem1: 'Manage Web Apps More Collaboration',
    tabListItem2: 'Update Web Hosting Collaboration',
    tabListItem3: 'Creative Web Domain Collaboration',
    premiumHosting: 'Premium <span class="text-base">Hosting</span>',
    premiumDesc: 'Choose the hosting plan that suits your business requirements and scale as you grow.',
    headerAccount: 'Account',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    footerServices: 'Services',
    footerVpsPlans: 'VPS Plans',
    footerDedicated: 'Dedicated Servers',
    footerPrivacy: 'Privacy',
    footerTerms: 'Terms & Conditions',
    copyrightBy: 'Copyright © 2025 | Designed by <a href="https://wa.me/+201029907297" ',
    enterpriseSolutions: 'Enterprise Solutions',
    premiumDedicatedServers: 'Premium Dedicated Servers',
    dedicatedDesc: 'Unmatched performance with exclusive hardware resources for your business',
    loadingDedicated: 'Loading Dedicated servers...',
    premiumChoice: 'Premium Choice',
    startingAt: 'Starting at',
    savePercent: 'Save {percent}%',
    processor: 'Processor',
    ramLabel: 'RAM',
    storageLabel: 'Storage',
    bandwidthLabel: 'Bandwidth',
    ipAddresses: 'IP Addresses',
    locationLabel: 'Location',
    fullRootAccess: 'Full Root Access',
    support247: '24/7 Support',
    configureServer: 'Configure Server',
    uptimeGuarantee: '99.9% Uptime Guarantee',
    exploreAllDedicated: 'Explore All Dedicated Servers',
    powerfulVpsServers: 'Powerful VPS Servers',
    vpsCarouselDesc: 'High-performance virtual private servers built for speed and reliability',
    loadingVps: 'Loading VPS plans...',
    mostPopular: 'Most Popular',
    highPerformanceVps: 'High-performance VPS',
    perMonth: 'Discount',
    vCpu: 'vCPU',
    ddosAndBackups: 'DDoS Protection & Daily Backups',
    moneyBack30: '24-Hours money-back guarantee',
    viewAllVps: 'View All VPS Servers',
    previousSlide: 'Previous slide',
    nextSlide: 'Next slide',
    managedPerformance: 'Managed Performance, Security, & Updates',
    fasterUnlimited: 'Faster Unlimited Services',
    performanceUnlimited: 'Performance & Unlimited hosting',
    ourDeals: 'Our Deals',
    bestVpsServers: "Don't miss the Best VPS Servers",
    moneyBackSupport: '24-Hours money-back guarantee | Cancel anytime | 24/7 support',
    bestEntry: 'Best Entry',
    lowSpaceStarter: 'Low Space Starter',
    perfectForTesting: 'Perfect for testing & small projects',
    mostStorage: 'MOST STORAGE',
    storageKing: 'Storage King',
    massiveStorage: 'Massive storage at lowest price',
    bestPerCore: 'Best $/Core',
    cpuChampion: 'CPU Champion',
    maxPowerPerDollar: 'Maximum CPU power per dollar',
    completeRange: 'Complete Range',
    allVpsPlans: 'All VPS Hosting Plans',
    found: 'found',
    noServersFound: 'No Servers Found',
    noVpsMatching: "We couldn't find any VPS plans matching your criteria",
    clearAllFilters: 'Clear All Filters',
    highPerformanceRoot: 'High performance & full root access',
    storageType: 'Storage Type',
    loadingPlans: 'Loading hosting plans...',
    '1monthPackage': '1 month pricing package',
    '3monthPackage': '3 months – Best value',
    '6monthPackage': '6 months – Maximum savings',
    perfectSolution: 'Perfect hosting solution',
    needHelp: 'Not Sure Which Plan to Choose?',
    helpChoosePlan: 'Our team is ready to help you pick the perfect plan',
    chatWithUs: 'Chat With Us',
    noPromos: 'No active promotions at the moment.',
    unableToLoadPromos: 'Unable to load hosting plans. Please try again.',
       contactUs: 'Contact Us',
    contactDesc: 'Have questions or need assistance? Get in touch with our support team. We\'re here to help!',
    emailSupport: 'Email Support',
    whatsappTelegram: 'WhatsApp & Telegram',
    liveSupport247: '24/7 Live Support',
    getInTouch: 'Get In',
    withUs: 'Touch',
    contactTeamDesc: 'Contact our team for support, inquiries, or partnership opportunities.',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    addressDetails: 'Egypt, Cairo',
    name: 'Name',
    enterYourName: 'Enter your name...',
    enterYourEmail: 'Enter your email...',
    enterYourPhone: 'Enter your phone (optional)',
    subject: 'Subject',
    enterSubject: 'Enter subject...',
    message: 'Message',
    writeYourMessage: 'Write your message here...',
    sendMessage: 'Send Message',
    contactUsNow: 'Contact Us Now',
    makeYour: 'Make Your',
    payment: 'Payment',
    easier: 'Easier & Faster',
    instantReceipt: 'Instant Receipt',
    securePayment: '100% Secure Payment',

    instapay: 'InstaPay',
    instapayDesc: 'Instant bank transfer via InstaPay network',
    vodafoneCash: 'Vodafone Cash',
    vodafoneCashDesc: 'Pay easily using your Vodafone Cash wallet',
    binance: 'Binance',
    binanceDesc: 'Cryptocurrency payments with instant receipt',
    "planName": "Plan Name",
    "selected": "selected",
    "clear": "clear",
    topDedicatedThisMonth: 'Top Dedicated Servers This Month',
    allDedicatedServers: 'All Dedicated Servers',
    moneyBackUptimeSupport: '24-Hours Money-Back · 99.9% Uptime · 24/7 Support',
    fullRoot100Dedicated: 'Full Root Access · 100% Dedicated',
    bestIntel: 'Best Intel Price',
    bestAmd: 'Best AMD Price',
    greatDeal: 'great Deal',
    bestPriceAmd: 'Best AMD Server Price',
    bestPriceIntel: 'Best Intel Server Price',
    lowestPricePerCore: 'Lowest Price Per Core',
    highPerformanceDeal: 'High Performance Deal',
    fullPower: 'Full Power',
    filter: 'Filter',
    getStartedNow: 'Get Started Now',
    "completeYourPurchase": "Complete Your Purchase",
    "checkout": "Checkout",
    "productSummary": "Product Summary",
    "cores": "CPU Core",
    "cores_plural": "CPU Cores",
    "storage": "Storage",
    "moneyBackGuarantee": "24-HOURS Money Back Guarantee",
    "technicalSupport": "24/7 Technical Support",
    "completeYourOrder": "Complete Your Order",
    "fullName": "Full Name",
    "enterFullName": "Enter your full name",
    "whatsappNumber": "WhatsApp Number",
    "enterWhatsapp": "01xxxxxxxxx",
    "selectPaymentMethod": "Select Payment Method",
    "paymentScreenshot": "Payment Screenshot",
    "clickToUpload": "Click to upload payment screenshot",
    "fileSelected": "Selected:",
    "remove": "Remove",
    "additionalNotes": "Additional Notes (Optional)",
    "notesPlaceholder": "Any special requirements or notes...",
    "back": "Back",
    "confirmOrder": "Confirm Order",
    "processing": "Processing...",
    "orderSuccess": "Order #{id} created successfully! We will contact you on WhatsApp soon.",
    "orderFailed": "Order failed. Please try again.",
    "pleaseSelectPayment": "Please select a payment method",
    "sendAmount": "Send:",
    "accountNumber": "Account Number",
    "accountName": "Account Name",
    "binanceId": "Binance ID",
    "binanceEmail": "Binance Email",
    "network": "Network",
    "loadingOrderDetails": "Loading order details...",
    specialOffers: 'Special Offers',
    discount: 'Discount',
    ourHostingPackages: 'Our Hosting Packages',
    limitedTimeDeals: 'Limited Time Deals',
    choosePerfectPlan: 'Choose the perfect plan for your needs',
    navdedicated: 'Dedicated',
    navvps: 'VPS',
    selectOperatingSystem: 'Select Operating System',
     instantActivation: 'Instant Activation',

  },
  ar: {
    home: 'الرئيسية',
    hosting: 'الاستضافة',
    dedicated: 'خوادم مخصصة',
    vps: 'خوادم VPS',
    promos: 'العروض',
    contact: 'اتصل بنا',
    orderNow: 'أحصل الآن',
    getStarted: 'ابدأ الآن',
    choosePlan: 'اختر الخطة',
    whyChoose: 'لماذا تختار TopServers لخوادم الاستضافة المخصصة؟',
    dedicatedIntro: 'توفر TopServers خوادمًا مخصصة موثوقة مع خيارات قابلة للتكوين للمعالج، والذاكرة، والتخزين والشبكة. اختر من التكوينات المعدة مسبقًا أو قم بالتصفية للعثور على الجهاز المناسب لاحتياجاتك.',
    filterServers: 'تصفية الخوادم',
    cpuCores: 'عدد نوى المعالج',
    ram: 'الذاكرة (جيجابايت)',
    brand: 'الماركة',
    maxPrice: 'أقصى سعر (دولار)',
    noDedicatedFound: 'لا توجد خوادم مخصصة.',
    fullBannerTitle: 'خدمة <span class="text-base">الاستضافة</span> المثالية لك',
    getHosting: 'احصل على استضافة',
    whyChooseUs: 'لماذا <span class="text-base">تختارنا</span>',
    chooseUsDesc: 'نقدم أكثر من الخوادم — الأداء والأمان والدعم لنجاحك على الإنترنت.',
    smartWorkTitle: 'عملنا الذكي',
    smartWorkDesc: 'أتمتة ذكية لأداء أمثل وإدارة خالية من المتاعب.',
    emailTitle: 'بريد إلكتروني احترافي',
    emailDesc: 'بريد إلكتروني احترافي مدرج مع كل خطة لبناء هوية علامتك التجارية.',
    supportTitle: 'دعم 24/7 مخصص',
    supportDesc: 'دعم خبراء على مدار الساعة من فريقنا الداخلي عند الحاجة.',
    serverProtectionTitle: 'حماية على مستوى الخادم',
    serverProtectionDesc: 'مراقبة أمان مؤسسية استباقية للدفاع ضد التهديدات الحديثة.',
    cloudIntegrationTitle: 'تكامل السحابة',
    cloudIntegrationDesc: 'بنية سحابية قابلة للتوسع ومرنة تنمو مع حركة المرور لديك.',
    hostingPlanTitle: 'خطة الاستضافة',
    hostingPlanDesc: 'اعثر على الخيار المناسب مع خططنا المرنة المصممة لمشروعاتك.',
    viewMoreAdvantages: 'عرض المزيد من المزايا',
    servicesTitle: 'خدماتنا',
    servicesDesc: 'اختر خطة الاستضافة التي تناسب احتياجاتك وميزانيتك.',
    tabDedicated: 'استضافة مخصصة',
    tabVps: 'استضافة VPS',
    tabDedicatedTitle: '<span class="text-base">مخصصة</span> استضافة',
    tabVpsTitle: '<span class="text-base">VPS</span> استضافة',
    tabListItem1: 'إدارة التطبيقات بمزيد من التعاون',
    tabListItem2: 'تحديث استضافة الويب',
    tabListItem3: 'دومين إبداعي',
    premiumHosting: 'استضافة <span class="text-base">مميزة</span>',
    premiumDesc: 'اختر خطة الاستضافة التي تناسب متطلبات عملك وقم بالتوسع عند النمو.',
    headerAccount: 'الحساب',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    footerServices: 'الخدمات',
    footerVpsPlans: 'خطط VPS',
    footerDedicated: 'الخوادم المخصصة',
    footerPrivacy: 'الخصوصية',
    footerTerms: 'الشروط والأحكام',
    copyrightBy: 'حقوق النشر © 2025 | مصمم بواسطة <a href="https://wa.me/+201029907297" class="underline">نوفا نود</a>',
    enterpriseSolutions: 'حلول المؤسسات',
    premiumDedicatedServers: 'خوادم مخصصة مميزة',
    dedicatedDesc: 'أداء لا مثيل له مع موارد أجهزة حصرية لأعمالك',
    loadingDedicated: 'جاري تحميل الخوادم المخصصة...',
    premiumChoice: 'الخيار المميز',
    startingAt: 'يبدأ من',
    savePercent: 'وفر {percent}%',
    processor: 'المعالج',
    ramLabel: 'الذاكرة',
    storageLabel: 'التخزين',
    bandwidthLabel: 'عرض النطاق الترددي',
    ipAddresses: 'عناوين IP',
    locationLabel: 'الموقع',
    fullRootAccess: 'صلاحية Root كاملة',
    support247: 'دعم 24/7',
    ddosProtection: 'حماية DDoS',
    configureServer: 'تهيئة الخادم',
    uptimeGuarantee: 'ضمان تشغيل 99.9%',
    exploreAllDedicated: 'استعرض جميع الخوادم المخصصة',
    powerfulVpsServers: 'خوادم VPS قوية',
    vpsCarouselDesc: 'خوادم افتراضية خاصة عالية الأداء مصممة للسرعة والموثوقية',
    loadingVps: 'جاري تحميل خطط VPS...',
    mostPopular: 'الأكثر شعبية',
    highPerformanceVps: 'VPS عالي الأداء',
    perMonth: 'خصم',
    vCpu: 'نواة افتراضية',
    ddosAndBackups: 'حماية DDoS والنسخ الاحتياطي اليومي',
    moneyBack30: 'ضمان استرداد الأموال خلال 24 ساعة',
    viewAllVps: 'عرض جميع خوادم VPS',
    previousSlide: 'الشريحة السابقة',
    nextSlide: 'الشريحة التالية',
    highPerformanceDedicated: 'استضافة مخصصة عالية الأداء',
    dedicatedResources: 'موارد مخصصة 100%',
    support247Monitoring: 'دعم ومراقبة 24/7',
    getStartedNow: 'ابدأ الآن',
    core: 'نواة',
    clearAll: 'مسح الكل',
    close: 'إغلاق',
    bestDeals: 'أفضل العروض هذا الشهر',
    topDedicatedThisMonth: 'أفضل الخوادم مخصصة هذا الشهر',
    moneyBackUptimeSupport: 'ضمان استرداد 24 ساعة · تشغيل 99.9% · دعم 24/7',
    bestIntel: 'أفضل سعر Intel',
    bestAmd: 'أفضل سعر AMD',
    bestValue: 'أفضل قيمة',
    greatDeal: 'عرض رائع',
    bestPriceIntel: 'أرخص سعر لخادم Intel',
    bestPriceAmd: 'أرخص سعر لخادم AMD',
    lowestPricePerCore: 'أقل سعر لكل نواة',
    highPerformanceDeal: 'عرض أداء عالي',
    fullPower: 'قوة كاملة',
    filter: 'فلتر',
    allDedicatedServers: 'جميع الخوادم المخصصة',
    server: 'خادم',
    available: 'متاح',
    applied: 'مُطبق',
    errorOccurred: 'عذرًا! حدث خطأ',
    tryAgain: 'حاول مرة أخرى',
    tryAdjustFilters: 'جرب تعديل الفلاتر أو إلغاؤها',
    clearFilters: 'مسح الفلاتر',
    fullRoot100Dedicated: 'صلاحية Root كاملة · 100% مخصص',
    limitedDeal: 'عرض لوقت محدود',
    managedPerformance: 'أداء مدار، أمان، وتحكم',
    fasterUnlimited: 'خدمات غير محدودة أسرع',
    performanceUnlimited: 'أداء واستضافة غير محدودة',
    ourDeals: 'عروضنا',
    bestVpsServers: 'لا تفوت أفضل خوادم VPS',
    moneyBackSupport: 'ضمان استرداد 24 ساعة | إلغاء في أي وقت | دعم 24/7',
    bestEntry: 'أفضل للمبتدئين',
    lowSpaceStarter: 'بداية مساحة منخفضة',
    perfectForTesting: 'مثالي للتجربة والمشاريع الصغيرة',
    mostStorage: 'أكبر مساحة',
    storageKing: 'ملك التخزين',
    massiveStorage: 'تخزين هائل بأقل سعر',
    bestPerCore: 'أفضل سعر/نواة',
    cpuChampion: 'بطل المعالج',
    maxPowerPerDollar: 'أقصى قوة معالجة لكل دولار',
    completeRange: 'النطاق الكامل',
    allVpsPlans: 'جميع خطط استضافة VPS',
    found: 'تم العثور عليه',
    noServersFound: 'لم يتم العثور على خوادم',
    noVpsMatching: 'لم نتمكن من العثور على أي خطط VPS تطابق معاييرك',
    clearAllFilters: 'مسح جميع الفلاتر',
    highPerformanceRoot: 'أداء عالي وصلاحية Root كاملة',
    storageType: 'نوع التخزين',
    needHelp: 'غير متأكد من الباقة المناسبة؟',
    helpChoosePlan: 'فريقنا جاهز لمساعدتك في اختيار الباقة المثالية',
    chatWithUs: 'تواصل معنا',
    loadingPlans: 'جاري تحميل باقات الاستضافة...',
   '1monthPackage': 'باقة شهر واحد',
    '3monthPackage': 'باقة 3 أشهر – أفضل قيمة',
    '6monthPackage': 'باقة 6 أشهر – أكبر توفير',

    contactUs: 'تواصل معنا',
    contactDesc: 'لديك أسئلة أو تحتاج مساعدة؟ تواصل مع فريق الدعم، نحن هنا لمساعدتك!',
    emailSupport: 'الدعم عبر البريد الإلكتروني',
    whatsappTelegram: 'واتساب وتيليجرام',
    liveSupport247: 'دعم مباشر 24/7',
    getInTouch: 'تواصل',
    withUs: 'معنا',
    contactTeamDesc: 'تواصل مع فريقنا للدعم، الاستفسارات، أو فرص الشراكة.',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    addressDetails: 'مصر، القاهرة',
    name: 'الاسم',
    enterYourName: 'أدخل اسمك...',
    enterYourEmail: 'أدخل بريدك الإلكتروني...',
    enterYourPhone: 'أدخل رقم هاتفك (اختياري)',
    subject: 'الموضوع',
    enterSubject: 'أدخل الموضوع...',
    message: 'الرسالة',
    writeYourMessage: 'اكتب رسالتك هنا...',
    sendMessage: 'إرسال الرسالة',
    contactUsNow: 'تواصل معنا الآن',
    makeYour: 'اجعل',
      payment: 'الدفع',
      easier: 'أسهل وأسرع',
      instantReceipt: 'استلام فوري',
      securePayment: 'دفع آمن 100%',

      instapay: 'إنستا باي',
      instapayDesc: 'تحويل بنكي فوري عبر شبكة إنستا باي',
      vodafoneCash: 'فودافون كاش',
      vodafoneCashDesc: 'ادفع بسهولة من محفظة فودافون كاش',
      binance: 'باينانس',
      binanceDesc: 'مدفوعات العملات الرقمية مع استلام فوري',
      "planName": "اسم الخطة",
      "selected": "مُحدد",
      "clear": "مسح",
      "completeYourPurchase": "إكمال عملية الشراء",
      "checkout": "إنهاء الطلب",
      "productSummary": "ملخص المنتج",
      "cores": "نواة معالج",
      "cores_plural": "نوى معالج",
      "storage": "التخزين",
      "moneyBackGuarantee": "ضمان استرداد الأموال خلال 24 ساعة",
      "technicalSupport": "دعم فني 24/7",
      "completeYourOrder": "إكمال الطلب",
      "fullName": "الاسم الكامل",
      "enterFullName": "أدخل اسمك الكامل",
      "whatsappNumber": "رقم الواتساب",
      "enterWhatsapp": "01xxxxxxxxx",
      "selectPaymentMethod": "اختر طريقة الدفع",
      "paymentScreenshot": "صورة إيصال الدفع",
      "clickToUpload": "اضغط لرفع صورة الإيصال",
      "fileSelected": "تم اختيار الملف:",
      "remove": "إزالة",
      "additionalNotes": "ملاحظات إضافية (اختياري)",
      "notesPlaceholder": "أي متطلبات خاصة أو ملاحظات...",

      "processing": "جاري المعالجة...",
      "orderSuccess": "تم إنشاء الطلب #{id} بنجاح! سنتواصل معك على الواتساب قريبًا.",
      "orderFailed": "فشل إنشاء الطلب. حاول مرة أخرى.",
      "pleaseSelectPayment": "يرجى اختيار طريقة دفع",
      "sendAmount": "أرسل:",
      "accountNumber": "رقم الحساب",
      "accountName": "اسم الحساب",
      "binanceId": "معرف باينانس",
      "binanceEmail": "بريد باينانس",
      "network": "الشبكة",
      "loadingOrderDetails": "جاري تحميل تفاصيل الطلب...",
      confirmOrder: "تأكيد الطلب",
      back: "عودة",
      specialOffers: 'عروض خاصة',
      discount: 'خصم',
      ourHostingPackages: 'باقات الاستضافة الخاصة بنا',
      limitedTimeDeals: 'عروض لفترة محدودة',
      choosePerfectPlan: 'اختر الباقة المثالية لاحتياجاتك',
      navdedicated: 'مخصصة',
      navvps: 'VPS',
      selectOperatingSystem: 'اختر نظام التشغيل',
       instantActivation: 'تفعيل فوري',

  }
};

@Injectable({
  providedIn: 'root'
})
export class TranslateService {
  private lang$ = new BehaviorSubject<Lang>('en');
  lang = this.lang$.asObservable();

  constructor() {
    // Read saved language or default to 'en'
    const savedLang = (localStorage.getItem('lang') as Lang) || 'en';
    this.lang$.next(savedLang);
    this.applyDirection(savedLang); // Critical: Apply direction on app start!
  }

  get current(): Lang {
    return this.lang$.value;
  }

  setLang(lang: Lang) {
    this.lang$.next(lang);
    localStorage.setItem('lang', lang);
    this.applyDirection(lang);
  }

  t(key: string): string {
    return DICT[this.current]?.[key] ?? DICT['en'][key] ?? key;
  }

  private applyDirection(lang: Lang) {
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }
}
